# Generated by Django 3.1 on 2021-05-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='slug',
            field=models.SlugField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
