# Generated by Django 3.1 on 2021-05-20 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_order_recall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recall',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='products.product'),
        ),
        migrations.AlterField(
            model_name='recall',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to=settings.AUTH_USER_MODEL),
        ),
    ]
